name: deploy
on:
  # On commit to the main branch
  push:
    branches:
      - main

jobs:
  docker-push:
    # For included software, refer to:
    # https://github.com/actions/virtual-environments/blob/ubuntu20/20210816.1/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
    permissions:
      packages: write
    env:
      IMAGE_NAME: codeorigin
      IMAGE_ID: ghcr.io/jquery/codeorigin
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t ${{ env.IMAGE_NAME }} ./

      - name: Test the container
        run: |
          docker run --rm -p 4000:80/tcp --detach ${{ env.IMAGE_NAME }}
          sleep 2
          curl -f --retry 5 --retry-delay 1 --retry-connrefused -I http://127.0.0.1:4000/jquery-3.0.0.js
          php test/CodeoriginTest.php

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
      - name: Login to Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
      - name: Publish image to Container Registry
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:latest
